import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:flutter/foundation.dart';

class AuthService {
  final FirebaseAuth _auth = FirebaseAuth.instance;

  // Stream of auth changes
  Stream<User?> get authStateChanges => _auth.authStateChanges();

  // Current user
  User? get currentUser => _auth.currentUser;

  // Sign in with Custom Token (generated by Python Bot)
  Future<UserCredential> signInWithCustomToken(String token) async {
    try {
      return await _auth.signInWithCustomToken(token);
    } catch (e) {
      debugPrint('Auth Error: $e');
      rethrow;
    }
  }

  // Sign in with Email & Password
  Future<UserCredential> signInWithEmailAndPassword(String email, String password) async {
    try {
      return await _auth.signInWithEmailAndPassword(email: email, password: password);
    } catch (e) {
       debugPrint('Email Auth Error: $e');
       rethrow;
    }
  }

  // Output: UserCredential
  // Register with Email & Password
  Future<UserCredential> createUserWithEmailAndPassword(String email, String password) async {
    try {
      final cred = await _auth.createUserWithEmailAndPassword(email: email, password: password);
      // Create user document in Firestore
      if (cred.user != null) {
        final username = email.split('@')[0];
        
        // 1. Create Firestore Doc
        await FirebaseFirestore.instance.collection('users').doc(cred.user!.uid).set({
          'email': email,
          'username': username,
          'first_name': username,
          'createdAt': FieldValue.serverTimestamp(),
          'role': 'user',
          'credits': 5, // Welcome bonus
          'pgmd': 1,
        });

        // 2. Send Verification Email
        if (!cred.user!.emailVerified) {
           await cred.user!.sendEmailVerification();
        }
      }
      return cred;
    } catch (e) {
       debugPrint('Registration Error: $e');
       rethrow;
    }
  }

  // Sign in with Google
  Future<UserCredential> signInWithGoogle() async {
    try {
      final GoogleSignIn googleSignIn = GoogleSignIn();
      
      // 1. Trigger the authentication flow
      print("Starting Google Sign In...");
      final GoogleSignInAccount? googleUser = await googleSignIn.signIn();
      
      if (googleUser == null) {
        // The user canceled the sign-in
        throw FirebaseAuthException(code: 'canceled', message: 'Вход отменен пользователем.');
      }
      print("Google User obtained: ${googleUser.email}");

      // 2. Obtain the auth details from the request
      final GoogleSignInAuthentication googleAuth = await googleUser.authentication;
      print("Google Auth obtained. AccessToken: ${googleAuth.accessToken != null}, IdToken: ${googleAuth.idToken != null}");

      // 3. Create a new credential
      final AuthCredential credential = GoogleAuthProvider.credential(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken,
      );
      print("Credential created.");

      // 4. Sign in to Firebase with the new credential
      final userCredential = await _auth.signInWithCredential(credential);
      print("Firebase Sign In Successful: ${userCredential.user?.uid}");
      
      // 5. Check if user doc exists, create if not
      if (userCredential.user != null) {
          final userDoc = await FirebaseFirestore.instance.collection('users').doc(userCredential.user!.uid).get();
          if (!userDoc.exists) {
             print("Creating new Firestore doc for Google user");
             await FirebaseFirestore.instance.collection('users').doc(userCredential.user!.uid).set({
                 'email': userCredential.user!.email,
                 'username': googleUser.email.split('@')[0],
                 'first_name': googleUser.displayName ?? 'User',
                 'createdAt': FieldValue.serverTimestamp(),
                 'role': 'user',
                 'credits': 5,
                 'pgmd': 1,
                 'telegram_id': null, 
             });
          }
      }

      return userCredential;
    } catch (e, stackTrace) {
      debugPrint('Google Auth Error: $e');
      debugPrint('Stack Trace: $stackTrace');
      
      // Re-throw with more context if possible
      if (e.toString().contains("Null check operator")) {
         throw Exception("Ошибка Google Sign-In (Null check): Попробуйте заново или проверьте сервисы Google.");
      }
      rethrow;
    }
  }

  // Reset Password
  Future<void> sendPasswordResetEmail(String email) async {
      await _auth.sendPasswordResetEmail(email: email);
  }

  /// Links a Telegram account (via Custom Token) to the current Google user.
  /// 
  /// Mechanics:
  /// 1. Use a secondary temporary Firebase App to sign in with the custom token.
  /// 2. This prevents disrupting the main user session.
  /// 3. Once signed in as Telegram User, write the Main User's UID to `users/{tg_id}/claimant_uid`.
  /// 4. This 'handshake' allows the Main User (via Rules) to then write `telegram_id` to their own profile.
  Future<void> linkTelegramAccount(String customToken) async {
    final currentUser = _auth.currentUser;
    if (currentUser == null) throw Exception("No user logged in");
    
    FirebaseApp? tempApp;
    try {
      // 1. Create a secondary app instance to verify the token without signing out main user
      tempApp = await Firebase.initializeApp(
        name: 'tempAuthLink',
        options: Firebase.app().options,
      );

      final tempAuth = FirebaseAuth.instanceFor(app: tempApp);
      
      // 2. Sign in with the Custom Token on the temp app
      final userCredential = await tempAuth.signInWithCustomToken(customToken);
      final telegramUser = userCredential.user;
      if (telegramUser == null) throw Exception("Failed to sign in with token");

      final String telegramUid = telegramUser.uid;
      final String mainUid = currentUser.uid;
      
      if (telegramUid == mainUid) {
         // Already same account? Unlikely if different providers, but check.
         throw Exception("Cannot link to self");
      }

      // 3. Handshake Step A: Telegram User writes "I am being claimed by MainUID"
      // We use a separate Firestore instance for the temp app to ensure we write AS the telegram user
      final tempFirestore = FirebaseFirestore.instanceFor(app: tempApp);
      await tempFirestore.collection('users').doc(telegramUid).set({
        'claimant_uid': mainUid,
        'linked_at': FieldValue.serverTimestamp(),
      }, SetOptions(merge: true));

      // 4. Handshake Step B: Main User (Google) writes "I lay claim to TelegramUID"
      // Firestore Rules will allow this ONLY if Step A occurred.
      await FirebaseFirestore.instance.collection('users').doc(mainUid).set({
        'telegram_id': telegramUid,
        'telegram_linked_at': FieldValue.serverTimestamp(),
      }, SetOptions(merge: true));

      // 5. DATA MIGRATION: Copy data from Telegram Account to Main Account
      await _migrateTelegramData(tempFirestore, telegramUid, mainUid);
      
      debugPrint("Link Success: $mainUid -> $telegramUid");

    } catch (e) {
      debugPrint("Link Error: $e");
      rethrow;
    } finally {
      // 6. Cleanup
      try {
        await tempApp?.delete();
      } catch (_) {}
    }
  }

  Future<void> _migrateTelegramData(FirebaseFirestore telegramDb, String sourceUid, String targetUid) async {
    final mainDb = FirebaseFirestore.instance;
    debugPrint("Starting Migration: $sourceUid -> $targetUid");

    // A. Profile Data (Credits, PGMD, Role)
    final sourceDoc = await telegramDb.collection('users').doc(sourceUid).get();
    if (!sourceDoc.exists) return; // Nothing to migrate

    final sourceData = sourceDoc.data()!;
    final int sourceCredits = sourceData['credits'] ?? 0;
    final int sourcePgmd = sourceData['pgmd'] ?? 0;
    final String? sourceRole = sourceData['role'];

    // Read target to merge smartly
    final targetRef = mainDb.collection('users').doc(targetUid);
    final targetDoc = await targetRef.get();
    final targetData = targetDoc.data() ?? {};
    final int currentCredits = targetData['credits'] ?? 0;
    final int currentPgmd = targetData['pgmd'] ?? 0;

    // Merge Logic:
    // Credits: Sum (Don't lose welcome bonus)
    // PGMD: Max (Take highest level)
    // Role: If source is admin, upgrade.
    
    final Map<String, dynamic> updates = {
      'credits': currentCredits + sourceCredits,
      'pgmd': (sourcePgmd > currentPgmd) ? sourcePgmd : currentPgmd,
    };
    if (sourceRole == 'admin') {
      updates['role'] = 'admin';
    }

    await targetRef.set(updates, SetOptions(merge: true));
    debugPrint("Profile Migrated: Credits ${currentCredits}+${sourceCredits}, PGMD $sourcePgmd");

    // B. Subcollection: Calculations (Diagnostic logs)
    final calcSnapshot = await telegramDb.collection('users').doc(sourceUid).collection('calculations').get();
    final batchSize = 500;
    var batch = mainDb.batch();
    int count = 0;

    for (var doc in calcSnapshot.docs) {
      final docRef = targetRef.collection('calculations').doc(doc.id); // Keep same ID
      batch.set(docRef, doc.data());
      count++;
      if (count >= batchSize) {
        await batch.commit();
        batch = mainDb.batch();
        count = 0;
      }
    }
    await batch.commit();
    debugPrint("Calculations Migrated: ${calcSnapshot.docs.length}");

    // C. Subcollection: Game History
    final histSnapshot = await telegramDb.collection('users').doc(sourceUid).collection('game_history').get();
    batch = mainDb.batch();
    count = 0;
    
    for (var doc in histSnapshot.docs) {
      final docRef = targetRef.collection('game_history').doc(doc.id);
      batch.set(docRef, doc.data());
       count++;
      if (count >= batchSize) {
        await batch.commit();
        batch = mainDb.batch();
        count = 0;
      }
    }
    await batch.commit();
    debugPrint("History Migrated: ${histSnapshot.docs.length}");
  }

  // Link Email & Password to existing account
  Future<void> linkEmailAndPassword(String email, String password) async {
      final user = _auth.currentUser;
      if (user == null) throw Exception("No user");
      
      try {
         final cred = EmailAuthProvider.credential(email: email, password: password);
         await user.linkWithCredential(cred);
         
         // Update Firestore
         await FirebaseFirestore.instance.collection('users').doc(user.uid).set({
            'email': email,
            'username': email.split('@')[0], // Set default username if missing
         }, SetOptions(merge: true));
         
      } catch (e) {
         debugPrint("Link Email Error: $e");
         rethrow;
      }
  }

  // Sign out
  Future<void> signOut() async {
    await _auth.signOut();
  }
}
