name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      
      # Use base-href if your repo is NOT user.github.io
      # If your repo is https://github.com/USER/REPO, use /REPO/
      # We will default to / currently, user might need to change if using Project Page
      - run: flutter build web --release --base-href "/"
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
